name: MacThermFlow
options:
  bundleIdPrefix: com.slmcamp
  deploymentTarget:
    macOS: "13.0"
targets:
  ThermFlowApp:
    type: application
    platform: macOS
    sources:
      - ThermFlowApp/Sources
      - ThermFlowApp/Assets.xcassets
    settings:
      PRODUCT_NAME: CoolCumber
      PRODUCT_BUNDLE_IDENTIFIER: com.slmcamp.CoolCumber
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: ThermFlowApp/Info.plist
      properties:
        CFBundleIconName: AppIcon
        NSHumanReadableCopyright: "Copyright © 2026 CoolCumber. All rights reserved."
        LSUIElement: true # Menu bar app
        LSApplicationCategoryType: "public.app-category.utilities"
        CFBundleURLTypes:
          - CFBundleURLName: "com.slmcamp.url"
            CFBundleURLSchemes:
              - coolcumber
    dependencies:
      - target: ThermFlowDaemon
        embed: false
      - target: ThermFlowWidget
        embed: true
    postBuildScripts:
      - script: |
          mkdir -p "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchServices"
          cp -f "${BUILT_PRODUCTS_DIR}/com.coolcumber.helper" "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchServices/com.coolcumber.helper"
          mkdir -p "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchDaemons"
          cp -f "${SRCROOT}/ThermFlowDaemon/LaunchDaemon.plist" "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchDaemons/com.coolcumber.helper.plist"
          cp -f "${SRCROOT}/ThermFlowDaemon/LaunchDaemon-Fallback.plist" "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchDaemons/com.coolcumber.helper-fallback.plist"
        name: Embed Daemon

  ThermFlowAppStore:
    type: application
    platform: macOS
    sources:
      - ThermFlowApp/Sources
      - ThermFlowApp/Assets.xcassets
    settings:
      PRODUCT_NAME: CoolCumber Lite
      PRODUCT_BUNDLE_IDENTIFIER: com.slmcamp.CoolCumber
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: APPSTORE
      ENABLE_APP_SANDBOX: YES
      CODE_SIGN_ENTITLEMENTS: ThermFlowApp/AppStore.entitlements
    info:
      path: ThermFlowApp/Info.plist
      properties:
        CFBundleIconName: AppIcon
        NSHumanReadableCopyright: "Copyright © 2026 CoolCumber. All rights reserved."
        LSUIElement: true # Menu bar app
        LSApplicationCategoryType: "public.app-category.utilities"
        CFBundleURLTypes:
          - CFBundleURLName: "com.slmcamp.url"
            CFBundleURLSchemes:
              - coolcumber
    dependencies:
      - target: ThermFlowWidget
        embed: true

  ThermFlowDaemon:
    type: tool
    platform: macOS
    sources: [ThermFlowDaemon/Sources]
    info:
      path: ThermFlowDaemon/Info.plist
    settings:
      CODE_SIGN_IDENTITY: "-"
      ENABLE_HARDENED_RUNTIME: NO
      CREATE_INFOPLIST_SECTION_IN_BINARY: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.coolcumber.helper
      PRODUCT_NAME: com.coolcumber.helper

  ThermFlowWidget:
    type: app-extension
    platform: macOS
    sources: [ThermFlowWidget/Sources]
    info:
      path: ThermFlowWidget/Info.plist
      properties:
        CFBundleDisplayName: "CoolCumber Widget"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      PRODUCT_NAME: CoolCumberWidget
      PRODUCT_BUNDLE_IDENTIFIER: com.slmcamp.CoolCumber.CoolCumberWidget
      ENABLE_APP_SANDBOX: YES
      CODE_SIGN_ENTITLEMENTS: ThermFlowWidget/Widget.entitlements
      SKIP_INSTALL: YES
